### DISCUSSION TITLE
Disable a worker in UI by dfault

### DISCUSSION THREAD

**Discussion by Th3ju** [pandora-analysis/pandora#791] [Q&A] [answered]
Hello,

First off all, thanks for this job !

Is it possible to disable some workers by default in the web UI ? (not totally disable)

For example, i don't want that Malware bazaar or Virus Total to be enable by default but if the user want it he can activate it in the advanced section. I've find how to totally disable a worker but not this kind off way.

Thank you in advance,

Regards
Ju

**Comment by Rafiot** [comment]
It's not possible at this stage, but would make sense to have a configurable list of modules on the submit page. Creating an issue for that.

**Reply by Rafiot** [reply, marked as answer]
Implemented. All the workers support these settings:

```yaml
settings:
  cache: 1h
  timeout: 1m
  # If required, the module will be run by default *and* cannot be disabled by the user
  required: false
  # Is true, the module is run by default, but can be disabled by the user
  run_by_default: true
  # The module is disabled, and the user cannot trigger it.
  disabled: false
```
