### ISSUE TITLE
[DOCKER] ClamAV Settings/Connection

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [pandora-analysis/pandora#126]
Hello,

i have another Docker question (sorry for that @Rafiot :-)

Since the ClamAV is running inside an own Docker Container (which make sense out of the docker perspective) i´m not able to use the Clamd socket of ClamAV from the Pandora Docker Container to get a connection. 

So in this case a TCP connection to the ClamAV docker container should rather be established ?

Thanks for your help.

**Comment by ITSEC-DACHSER** [comment]
@FafnerKeyZee  Thanks for your answer!
Allright, i understand. Both container has the same volume and mount the hosts "/tmp" which includes the clamav socket file.

In my case the volume IS mounted on both on containers as defined in the docker-compose file. 
The file is called "clamd.sock". 

Here the view out of the pandora container:
![image](https://user-images.githubusercontent.com/50357205/199024497-96b082e6-e205-4a5f-a420-f3f262bd8940.png)

So i set the config for ClamAV to this:
```

# cat /home/pandora/pandora/workers# cat clamav.yml
meta:

  name: ClamAV
  description: Local ClamAV scanner
  replicas: 1

settings:
#  socket_path: /var/run/clamav/clamd.ctl
  socket_path: /var/run/clamav/clamd.sock

```
If i then restart the pandora  container after this change, the pandora website will not came up again. 
There is also no error inside the docker logs. Maybe i did something wrong.
