### ISSUE TITLE
[Worker] default timeout for Preview

### ISSUE THREAD

**Issue by FafnerKeyZee** [pandora-analysis/pandora#304]
Hello,

With the following config
```
meta:
  name: Preview
  description: Generates a preview for the uploaded document (office, pdf, image, ...)
  replicas: 5

```
If the file is too big the worker never stop. Is there any fallback for the timeout ?

BR
