### ISSUE TITLE
Waiting on storage to start kvrocks

### ISSUE THREAD

**Issue by FR0ST-0** [pandora-analysis/pandora#399]
Hi, I have a problem with the docker compose file on Kvrocks.
It gives me the following error:
```Start backend (redis)...
 Waiting on storage to start
 + test -f ../kvrocks/build/kvrocks
 + ../../kvrocks/src/kvrocks -c kvrocks.conf
 ./run_kvrocks.sh: line 9: ../../kvrocks/src/kvrocks: No such file or directory
 Waiting on storage to start
 Waiting on storage to start
 Waiting on storage to start
```
But before the I had to change the image on the docker compose image of kvrocks from ```image: kvrocks/kvrocks``` to ```image: apache/kvrocks``` since the other image would exit.

Can anyone help me with this problem?

**Comment by FR0ST-0** [comment]
Yes, i saw that the folder ```kvrocks``` on ```kvrocks/src/kvrocks``` does not exist.
I also edited the file located on ```pandora/storage/run_kvrocks.sh``` and if you remove the last folder ```kvrocks``` it gives this error: 
```Start backend (redis)...
+ ../../redis/src/redis-server ./cache.conf
+ test -f ../kvrocks/build/kvrocks
+ ../kvrocks/src/ -c kvrocks.conf
./run_kvrocks.sh: line 9: ../kvrocks/src/: No such file or directory
Waiting on cache to start
Waiting on storage to start
```
But it also gives the same error when i installed the Pandora from source, I did all the installation steps and at first it worked perfectly, but when i restarted the machine the Kvrocks stopped working.
So i think that the problem is from Kvrocks, but I am  stuck at the moment.

**Comment by Rafiot** [comment]
Alright, I know what's going on. 

* `../../kvrocks/src/kvrocks` is the old location (I'm removing that from the script, this version isn't working anymore)
* `../../kvrocks/build/kvrocks` is the place where kvrocks should be if it is compiled.

I'm not sure how the docker image is supposed to work, but I'll have a look later.

**Comment by FR0ST-0** [comment]
Thanks, at the moment I will try and see if i can get it up and running, if I do so, i will but the resolution here.
If not, I will wait for the solution.

**Comment by Rafiot** [comment]
I cannot promise the docker install will work. You said you got it to work initially, so you will probably get it back up.

**Comment by FR0ST-0** [comment]
I only got the source installation to work before the restarting the machine, but the docker it never worked.

**Comment by Rafiot** [comment]
just making sure: kvrocks must be in the same directory as pandora, and not in the pandora directory

**Comment by FR0ST-0** [comment]
Yes it is, I did it like it was done in the installation.

**Comment by samuelmonsempessenthorus** [comment]
Now I have the same problem:

**Version:**
Latest

**Step to reproduce:**
git clone https://github.com/pandora-analysis/pandora.git
cd pandora
cp ./config/generic.json.sample ./config/generic.json
sudo docker compose up

**Issue:**
 ./run_kvrocks.sh: line 9: ../../kvrocks/src/kvrocks: No such file or directory

**Why this happen:**
Pandora try to run kvrocks in his container which is weird because kvrocks is already running on another container

I'm trying to fix this but I'm pretty new to this project !

PS: Thank you very much for resolving issue 429 so quickly!

**Comment by samuelmonsempessenthorus** [comment]
Edit: 
**Why this happen:**
in the check_running function in run_backend it can't ping kvrocks


I try to change the kvrocks port from 6666 to 6101 it don't work

**Comment by samuelmonsempessenthorus** [comment]
Ok, it seems that there are several problems:
* The kvrocks docker expose port 6666 and not 6101
* There is an issue on the docker kvrocks binding related to this kvrocks issue [https://github.com/apache/kvrocks/issues/1905](url)


Here is my new docker-compose, it's still not work but at list I can connect myself to krocks with "redis-cli -p 6101"
```

version: '3'
services:

  kvrocks:
    image: apache/kvrocks
    working_dir: /kvrocks
    volumes:
        - ./storage:/kvrocks/conf
    ports:
        - 6101:6666
    command: "--bind 0.0.0.0"
  redis:
    image: redis
    working_dir: /cache
    command: ./cache.conf --daemonize no
    volumes:
        - ./cache:/cache
  clamav:
    image: clamav/clamav
    volumes:
        - clamav-socket:/tmp

  pandora:
    build: .
    working_dir: /pandora
    tty: true
    command:
        - /bin/sh
        - -c
        - |
            sleep 60
            poetry run start
            tail -F ./LICENSE
    volumes:
        - ./cache:/pandora/cache
        - ./storage:/pandora/storage
        - ./pandora/workers:/pandora/pandora/workers
        - ./config:/pandora/config
        - ./yara_rules:/pandora/yara_rules
        - ./yara_repos:/pandora/yara_repos
        - ./logs:/pandora/logs
        - ./web_logs:/pandora/website/logs
        - ./tasks:/pandora/tasks
        - clamav-socket:/var/run/clamav
    links:
        - "clamav"
        - "redis"
        - "kvrocks"
    ports:
        - 6100:6100

volumes:
    clamav-socket:

```
